# in _config.yml
title: "Good research code"
author: "Patrick Mineault"

execute:
  execute_notebooks: "cache"

repository:
  url                       : "https://github.com/patrickmineault/repl-test"  # Online location of your book
  path_to_book              : .  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

html:
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://locahost:8888/
  favicon: images/favicon.ico
  use_fullscreen_button: false

launch_buttons:
  thebe             : true
  notebook_interface: classic

thebe_config:
  repository_url : "https://github.com/patrickmineault/repl-test"  # Online location of your book
  path_to_book   : "docs/"  # Optional path to your book, relative to the repository root
  branch         : main  # Which branch of the repository should be used when creating links (optional)
