# in _config.yml
title: "Good research code"
author: "<a href='https://xcorr.net'>Patrick Mineault</a> <a href='https://twitter.com/patrickmineault'><img height='24' width='24' src='_images/twitter.svg' alt='Twitter' style='width:24px'></a>"
copyright: "2021"
logo: figures/unicorn.png

execute:
  execute_notebooks: "auto"

repository:
  url                       : "https://github.com/patrickmineault/repl-test"  # Online location of your book
  path_to_book              : .  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

html:
  google_analytics_id: G-3Q6LDVNS0X
  home_page_in_navbar: true
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://goodresearch.dev/
  favicon: images/favicon.ico
  use_fullscreen_button: false
  comments:
    hypothesis: false
  extra_footer: "Licensed under <a href='https://github.com/patrickmineault/codebook/blob/main/LICENSE'>CC-BY 4.0</a> [<a href='https://github.com/patrickmineault/codebook'>source</a>].<br /><a href='https://github.com/patrickmineault/codebook/issues'>Report issue</a>."

launch_buttons:
  thebe             : true
  notebook_interface: classic

thebe_config:
  repository_url : "https://github.com/patrickmineault/repl-test"  # Online location of your book
  path_to_book   : "docs/"  # Optional path to your book, relative to the repository root
  branch         : main  # Which branch of the repository should be used when creating links (optional)

parse:
  myst_enable_extensions:
    - colon_fence
    - substitution
    - dollarmath
    - deflist
    - html_image

sphinx:
  extra_extensions:
  - sphinxext.opengraph
  config:
    ogp_site_url: "https://goodresearch.dev/"
    ogp_image: "https://goodresearch.dev/_images/unicorn.png"
    ogp_description_length: 200